"""bizup cost engine — pure Python hexagonal core.

AD-1:  Hexagonal core. Pure domain logic; ports for inbound/outbound; adapters at boundary.
AD-5:  Engine purity — no I/O, no DB, no clock, no randomness, no global state, no logs.
AD-11: Dependency direction — `core` may NOT import `adapters`. Enforced by import-linter.

This package is the source of truth for the 1원 reconciliation (V8 regression).

Public API (Story 4.1):
  - compute_period_cost(monthly_input, baseline) -> CalcResult (pure kernel)
  - MonthlyInput / CalcResult / Baseline dataclasses
  - KRW / USD NewType monetary primitives

Public API (Story 8.1):
  - derive_budget_period_key / parse_virtual_budget_period_key / validate_scenario_uniqueness / compute_budget_scenario_hash
  - BudgetPeriodKeyParts / BudgetScenario frozen dataclasses
  - ScenarioLimitExceededError / InvalidVirtualBudgetPeriodKeyError typed exceptions
"""

from packages.cost_engine.abc_engine import (
    ABC_HASH_PREFIX,
    ABC_PRECISION_KRW_TOLERANCE,
    ABC_VALIDATION_KRW_QUANTUM,
    ALLOCATION_PCT_MAX,
    ALLOCATION_PCT_MIN,
    CCR_HASH_PREFIX,
    CCR_KRW_QUANTUM,
    MAX_DEPARTMENT_COUNT,
    REPORT15_HASH_PREFIX,
    REPORT_PDF_HASH_PREFIX,
    V7_BALANCE_TOLERANCE_KRW,
    VALIDATION_100_PCT_TARGET,
    VALIDATION_DEFAULT_INDUSTRY,
    VALIDATION_HASH_PREFIX,
    VALIDATION_TOLERANCE_KRW,
    AbcValidationNotFoundError,
    ActivityCostRow,
    ActivityMapping,
    ActivityValidation,
    ActivityValidationError,
    AllocationBalanceError,
    AllocationResult,
    AllocationState,
    CcrComputeError,
    CCRResult,
    CostObjectRow,
    CostPoolValidation,
    CostPoolValidationError,
    DepartmentAllocation,
    DispatchState,
    DriverValidation,
    DriverValidationError,
    EmptyDepartmentsError,
    MultiDepartmentCcrResult,
    Report15InconsistentStateError,
    Report15Summary,
    Report21InconsistentStateError,
    Report21Summary,
    TooManyDepartmentsError,
    UnusedCapacityRow,
    UnusedCapacitySubRow,
    V7Verdict,
    ValidationState,
    aggregate_multi_department_ccr,
    compute_abc_allocation_hash,
    compute_allocation,
    compute_allocation_hash,
    compute_ccr,
    compute_ccr_hash,
    compute_report15_hash,
    compute_report21_hash,
    compute_report_pdf_hash,
    compute_validation_hash,
    dispatch_abc_path,
    produce_unused_capacity_row,
    validate_100_percent_guard,
    validate_activity,
    validate_cost_pool,
    validate_department_count,
    validate_driver,
    verify_v7_balance,
)
from packages.cost_engine.budget_period_key import (
    BudgetPeriodKeyParts,
    BudgetScenario,
    InvalidVirtualBudgetPeriodKeyError,
    ScenarioLimitExceededError,
    compute_budget_scenario_hash,
    derive_budget_period_key,
    parse_virtual_budget_period_key,
    validate_scenario_uniqueness,
)
from packages.cost_engine.budget_pre_standard import (
    OVERHEAD_RATE_MAX_PCT,
    OVERHEAD_RATE_MIN_PCT,
    PRE_STANDARD_DEFAULT_BASELINE_REVISION,
    PRE_STANDARD_DEFAULT_SCENARIO_INDEX,
    PRE_STANDARD_ENGINE_TYPE,
    PRE_STANDARD_HASH_PREFIX,
    PRE_STANDARD_KRW_QUANTUM,
    PRE_STANDARD_STATE_VERIFIED,
    EngineType,
    InvalidPreStandardInputError,
    PreStandardCost,
    compute_pre_standard_cost,
    compute_pre_standard_hash,
)
from packages.cost_engine.budget_variance import (
    ABCD_DISABLED_LABEL,
    ABCD_DISABLED_NOTE,
    ABCD_DISABLED_TOOLTIP,
    SEVERITY_THRESHOLD_CRITICAL_PCT,
    SEVERITY_THRESHOLD_WARNING_PCT,
    VARIANCE_HASH_PREFIX,
    VARIANCE_PCT_QUANTUM,
    ABCDDisabledBadge,
    Variance,
    VarianceRow,
    compute_abcd_disabled_badge,
    compute_variance,
    compute_variance_color,
    compute_variance_hash,
)
from packages.cost_engine.core.money import KRW, USD
from packages.cost_engine.core.period_cost import (
    Baseline,
    compute_period_cost,
)
from packages.cost_engine.cvp import (
    FIXED_COST_DELTA_PCT_BOUNDS,
    OPERATING_RATE_DELTA_PCT_BOUNDS,
    PRICE_DELTA_PCT_BOUNDS,
    BEPResult,
    CVPBaseline,
    CVPDelta,
    CVPInvalidInputError,
    CVPResult,
    TargetProfitResult,
    apply_delta,
    compute_bep,
    compute_bep_hash,
    compute_target_profit,
    simulate_cvp,
)
from packages.cost_engine.ports.calc_port import CalcResult, MonthlyInput
from packages.cost_engine.projection import (
    PROJECTION_COST_INFLATION_RATE_MAX_PCT,
    PROJECTION_COST_INFLATION_RATE_MIN_PCT,
    PROJECTION_HASH_PREFIX,
    InvalidProjectionMonthError,
    NextMonthProjection,
    ProjectionBaselineNotFoundError,
    ProjectionInputs,
    ProjectionInvalidInputError,
    compute_after_tax_income,
    compute_interest_expense,
    compute_projection_hash,
    project_next_month,
)

__all__ = [
    # Story 4.1 pure kernel
    "compute_period_cost",
    "Baseline",
    # I/O dataclasses
    "MonthlyInput",
    "CalcResult",
    # Monetary primitives
    "KRW",
    "USD",
    # Story 8.1 budget period key pure kernel
    "derive_budget_period_key",
    "parse_virtual_budget_period_key",
    "validate_scenario_uniqueness",
    "compute_budget_scenario_hash",
    "BudgetPeriodKeyParts",
    "BudgetScenario",
    "ScenarioLimitExceededError",
    "InvalidVirtualBudgetPeriodKeyError",
    # Story 7.1 CVP/BEP pure kernel
    "compute_bep",
    "compute_target_profit",
    "apply_delta",
    "simulate_cvp",
    "compute_bep_hash",
    "BEPResult",
    "TargetProfitResult",
    "CVPBaseline",
    "CVPDelta",
    "CVPResult",
    "CVPInvalidInputError",
    "PRICE_DELTA_PCT_BOUNDS",
    "FIXED_COST_DELTA_PCT_BOUNDS",
    "OPERATING_RATE_DELTA_PCT_BOUNDS",
    # Story 7.2 Next-Month Projection pure kernel
    "compute_interest_expense",
    "compute_after_tax_income",
    "project_next_month",
    "compute_projection_hash",
    "ProjectionInputs",
    "NextMonthProjection",
    "ProjectionInvalidInputError",
    "InvalidProjectionMonthError",
    "ProjectionBaselineNotFoundError",
    "PROJECTION_HASH_PREFIX",
    "PROJECTION_COST_INFLATION_RATE_MIN_PCT",
    "PROJECTION_COST_INFLATION_RATE_MAX_PCT",
    # Story 8.2 Budget Variance pure kernel
    "compute_variance",
    "compute_variance_color",
    "compute_variance_hash",
    "compute_abcd_disabled_badge",
    "Variance",
    "VarianceRow",
    "ABCDDisabledBadge",
    "SEVERITY_THRESHOLD_WARNING_PCT",
    "SEVERITY_THRESHOLD_CRITICAL_PCT",
    "VARIANCE_PCT_QUANTUM",
    "VARIANCE_HASH_PREFIX",
    "ABCD_DISABLED_LABEL",
    "ABCD_DISABLED_TOOLTIP",
    "ABCD_DISABLED_NOTE",
    # Story 8.3 Budget Pre-Standard Cost pure kernel
    "compute_pre_standard_cost",
    "compute_pre_standard_hash",
    "PreStandardCost",
    "EngineType",
    "InvalidPreStandardInputError",
    "PRE_STANDARD_KRW_QUANTUM",
    "OVERHEAD_RATE_MIN_PCT",
    "OVERHEAD_RATE_MAX_PCT",
    "PRE_STANDARD_ENGINE_TYPE",
    "PRE_STANDARD_DEFAULT_SCENARIO_INDEX",
    "PRE_STANDARD_HASH_PREFIX",
    "PRE_STANDARD_STATE_VERIFIED",
    "PRE_STANDARD_DEFAULT_BASELINE_REVISION",
    # Story 9.1 ABC 100% Validation pure kernel (A19 cohesion pattern 6번째)
    "validate_cost_pool",
    "validate_activity",
    "validate_driver",
    "compute_validation_hash",
    "validate_100_percent_guard",
    "CostPoolValidation",
    "ActivityValidation",
    "DriverValidation",
    "ValidationState",
    "CostPoolValidationError",
    "ActivityValidationError",
    "DriverValidationError",
    "AbcValidationNotFoundError",
    "ABC_VALIDATION_KRW_QUANTUM",
    "ALLOCATION_PCT_MIN",
    "ALLOCATION_PCT_MAX",
    "VALIDATION_100_PCT_TARGET",
    "VALIDATION_TOLERANCE_KRW",
    "VALIDATION_HASH_PREFIX",
    "VALIDATION_DEFAULT_INDUSTRY",
    # Story 9.2 ABC Allocation pure kernel (A19 cohesion pattern 7 surface)
    "compute_ccr",
    "compute_ccr_hash",
    "produce_unused_capacity_row",
    "compute_allocation",
    "compute_allocation_hash",
    "CCRResult",
    "ActivityMapping",
    "CostObjectRow",
    "AllocationResult",
    "UnusedCapacityRow",
    "AllocationState",
    "CcrComputeError",
    "AllocationBalanceError",
    "CCR_KRW_QUANTUM",
    "ABC_PRECISION_KRW_TOLERANCE",
    "CCR_HASH_PREFIX",
    # Story 9.3 ABC Dispatch pure kernel (A19 cohesion pattern 7 surface 누적)
    "verify_v7_balance",
    "aggregate_multi_department_ccr",
    "dispatch_abc_path",
    "validate_department_count",
    "compute_abc_allocation_hash",
    "V7Verdict",
    "MultiDepartmentCcrResult",
    "DispatchState",
    "DepartmentAllocation",
    "UnusedCapacitySubRow",
    "EmptyDepartmentsError",
    "TooManyDepartmentsError",
    "V7_BALANCE_TOLERANCE_KRW",
    "MAX_DEPARTMENT_COUNT",
    "ABC_HASH_PREFIX",
    # Story 9.4 ABC Report #21 (Cost Object Breakdown) pure kernel
    "compute_report21_hash",
    "compute_report_pdf_hash",
    "Report21Summary",
    "Report21InconsistentStateError",
    "REPORT_PDF_HASH_PREFIX",
    # Story 11.6 ABC Report #15 (활동원가 내역서) pure kernel
    # A33 forward-lock (A19 cohesion 9 surface) 진입점 결정 wire
    "compute_report15_hash",
    "ActivityCostRow",
    "Report15Summary",
    "Report15InconsistentStateError",
    "REPORT15_HASH_PREFIX",
]
