"""apps.api.core.db_models — SQLAlchemy 2.0 ORM models (Story 0.2 + 1.3 + 2.1 + 2.2 + 3.1).

Mapped tables:
- 0001: tenants, users, tenant_memberships, tenant_settings, audit_logs
- 0005 (Story 1.3): uploaded_documents, input_drafts
- 0006 (Story 2.1): products
- 0007 (Story 2.2): bom_lines
- 0009 (Story 3.1): monthly_input_periods, monthly_input_rows

Per AD-1/AD-11: this module is in `apps/api/` (infra layer). It does NOT
import `packages.cost_engine` directly. Modules write through services.

Per AD-15: snake_case column names; UUID v4 for `tenant_id` (derived from
JWT, never from request body); UUID v7 for new business entities
(`document_id`, `draft_id`, `id` of `products`, `id` of `bom_lines`) —
generated by `packages.common.uuid7`.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Integer,
    LargeBinary,
    Numeric,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from packages.common.uuid7 import uuid7 as _uuid7


class Base(DeclarativeBase):
    """Common ORM base for all apps/api models."""


# ── tenants ────────────────────────────────────────────────
class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    industry: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "industry IN ('manufacturing', 'manufacturing_retail', 'service', 'mixed')",
            name="tenants_industry_check",
        ),
    )


# ── users ──────────────────────────────────────────────────
class User(Base):
    __tablename__ = "users"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    # tenant_id is NULLABLE for cross-tenant users (e.g. consultant_proxy
    # before they join a tenant). RLS policy filters to current tenant when
    # tenant_id IS NOT NULL.
    tenant_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=True,
    )
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    twofa_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "role IN ('owner', 'member', 'viewer', 'consultant_proxy')",
            name="users_role_check",
        ),
    )


# ── tenant_memberships ─────────────────────────────────────
class TenantMembership(Base):
    __tablename__ = "tenant_memberships"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    joined_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        UniqueConstraint("tenant_id", "user_id", name="tenant_memberships_tenant_user_key"),
    )


# ── tenant_settings (AD-23) ───────────────────────────────
class TenantSettings(Base):
    __tablename__ = "tenant_settings"

    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        primary_key=True,
    )
    settings_version: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=1
    )  # F-17: BigInteger to prevent int4 overflow on long-lived tenants
    onboarding: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    baseline: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    abc: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    ai: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── audit_logs (AD-2) ─────────────────────────────────────
class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    tenant_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="SET NULL"),
        nullable=True,
    )
    actor_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    target_table: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── uploaded_documents (Story 1.3 — Task 1.2) ───────────────
# One row per uploaded file (PDF / image). Carries the Supabase Storage
# path + sha256 of the bytes (for the `409 DOCUMENT_ALREADY_EXISTS`
# re-upload guard) + retention metadata.
#
# AD-15: document_id is UUID v7 (time-ordered) — better B-tree locality
# for the dashboard's newest-first query. Default is the stdlib helper
# `packages.common.uuid7.uuid7()` so the application never needs to
# remember to set it.
class UploadedDocument(Base):
    __tablename__ = "uploaded_documents"

    document_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    storage_path: Mapped[str] = mapped_column(Text, nullable=False)
    mime_type: Mapped[str] = mapped_column(Text, nullable=False)
    byte_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content_sha256: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Provider job status — separate from `input_drafts.state` per spec Task 1.2.
    job_status: Mapped[str] = mapped_column(
        Text, nullable=False, default="queued"
    )
    uploaded_by: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    # Story 1.3 — Idempotency-Key header support (Task 3.1 / AC #2).
    # Partial unique index enforces dedupe at the DB layer; non-unique
    # when NULL so clients that omit the header still get a fresh row.
    idempotency_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    error_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message_ko: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "job_status IN ('queued', 'processing', 'completed', 'failed')",
            name="uploaded_documents_job_status_check",
        ),
        CheckConstraint("byte_size > 0", name="uploaded_documents_byte_size_positive"),
    )


# ── input_drafts (Story 1.3 — Task 1.2 / AD-7) ───────────────
# One row per AI-extracted field. AD-7 + AD-7-ai-extraction-table-naming.md
# declare `input_drafts` canonical. ERD §8 `ai_extractions.pending_review`
# / `approved` is superseded — see the AD for the mapping.
#
# State machine: draft → reviewed → superseded (3 states, not 2).
# `promoted` is intentionally absent — that's an AD-17 monthly-input semantic.
class InputDraft(Base):
    __tablename__ = "input_drafts"

    draft_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    document_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("uploaded_documents.document_id", ondelete="CASCADE"),
        nullable=False,
    )
    field_name: Mapped[str] = mapped_column(Text, nullable=False)
    ai_value: Mapped[dict] = mapped_column(JSONB, nullable=False)
    confirmed_value: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # NUMERIC(4,3) — 4 digits total, 3 after the decimal → covers 0.000..9.999
    # with the CHECK constraint restricting to [0, 1]. Use Decimal for AD-8 parity.
    confidence: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=4, scale=3), nullable=True
    )
    state: Mapped[str] = mapped_column(Text, nullable=False, default="draft")
    evidence: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    draft_hash: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    requested_by: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    reviewed_by: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True), nullable=True
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        CheckConstraint(
            "state IN ('draft', 'reviewed', 'superseded')",
            name="input_drafts_state_check",
        ),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="input_drafts_confidence_range_check",
        ),
    )


# ── products (Story 2.1 — Tasks 3.1 / 3.2) ──────────────────
# One row per registered product/item. AD-18 single product identity:
# `id` (UUID v7) is the sole key referenced by BOM (Story 2.2),
# inventory ledger (Story 2.2+), and reports (Epic 6).
#
# `code` is a per-tenant per-type sequence (PRD §8.M1) — NOT the primary
# key. Tenants may share codes across tenant boundaries; the unique index
# `(tenant_id, code)` enforces intra-tenant uniqueness.
#
# Money columns are AD-8 strict: KRW = BIGINT (no fractional won), USD =
# NUMERIC(18,2) (2 decimal places, ROUND_HALF_EVEN per chunk-B).
class Product(Base):
    __tablename__ = "products"

    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    product_type: Mapped[str] = mapped_column(Text, nullable=False)
    code: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    # AD-8: KRW stored as BIGINT (no fractional won). TS uses `bigint`.
    unit_cost_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # AD-8: USD stored as NUMERIC(18,2). Decimal-typed; rounded at the
    # service boundary (ROUND_HALF_EVEN, Story 0.4 chunk-B).
    unit_cost_usd: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=18, scale=2), nullable=True
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Soft-delete flag (AC #5). Hard delete is forbidden (AD-2 append-only).
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "product_type IN ('product', 'semi_product', 'material', 'goods', 'service')",
            name="products_product_type_check",
        ),
        CheckConstraint(
            "length(name) BETWEEN 1 AND 200",
            name="products_name_length_check",
        ),
        CheckConstraint(
            "unit IS NULL OR length(unit) <= 20",
            name="products_unit_length_check",
        ),
        CheckConstraint(
            "unit_cost_krw IS NULL OR unit_cost_krw >= 0",
            name="products_unit_cost_krw_nonneg",
        ),
        CheckConstraint(
            "unit_cost_usd IS NULL OR unit_cost_usd >= 0",
            name="products_unit_cost_usd_nonneg",
        ),
        CheckConstraint(
            "description IS NULL OR length(description) <= 2000",
            name="products_description_length_check",
        ),
        # AC #3 — same-tenant code uniqueness. RLS-scoped (NOT global).
        UniqueConstraint(
            "tenant_id", "code", name="uq_products_tenant_code"
        ),
    )


# ── bom_lines (Story 2.2 — Task 2.2) ────────────────────────────
# One row per (parent_product, child_product) link. AD-18 single product
# identity: both FKs point at `products.id` (UUID v7).
#
# `ratio` is `NUMERIC(7,4)` (AD-8 extended) — 4 decimal places, max
# 100.0000. CHECK `0 < ratio <= 100`. Python `Decimal`. Quantize via
# `ROUND_HALF_EVEN` per Story 0.4 chunk-B.
#
# Append-only-leaning (AD-2): the bulk-replace PUT semantics mean DELETE
# is a service-layer operation, not a per-row endpoint. RLS has no DELETE
# policy; the UNIQUE INDEX is the only duplicate-children defense at the
# DB layer (the service pre-validates for typed 422 responses).
class BOMLine(Base):
    __tablename__ = "bom_lines"

    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    # AD-18: both FKs to products.id (UUID v7). ON DELETE RESTRICT —
    # hard-deleting a product is forbidden (AD-2); soft-delete preserves
    # BOM history (Story 2.1 AC #5 + Story 2.2 AC #9).
    parent_product_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
    )
    child_product_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
    )
    # AD-8 — ratio is NUMERIC(7,4). Decimal-typed in both Python and TS.
    # `Decimal` is imported above; mapped_column handles the SQL type.
    ratio: Mapped[Decimal] = mapped_column(
        Numeric(precision=7, scale=4), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "ratio > 0 AND ratio <= 100",
            name="bom_lines_ratio_range_check",
        ),
    )


# ── monthly_input_periods (Story 3.1 — Task 2.1) ──────────────
# One row per (tenant, period_key, baseline_revision) triple.
# AD-23 4-namespace: uniqueness on the triple keeps each tenant's
# periods fully isolated. Multiple revisions of the same period can
# coexist (Epic 4 first_calc bumps `baseline_revision` and keeps the
# previous row for V8 regression comparison).
#
# `mode` carries the F2.1 일자별/월합계 toggle. Switching does NOT
# create a new revision — it's a per-period UI preference (not a
# baseline change). `baseline_revision` only bumps at first_calc time
# (Story 3.4 + Epic 4).
#
# `locked_by_calculation`: AD-13 says MonthInputAdapter reads but
# doesn't lock — Epic 4 M3 calc sets this true so the UI can show
# "마감됨" badge and disable edits. Epic 3.1 only INSERTs with default
# `false`.
class MonthlyInputPeriod(Base):
    __tablename__ = "monthly_input_periods"

    period_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    mode: Mapped[str] = mapped_column(
        Text, nullable=False, default="month_total"
    )
    baseline_revision: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1
    )
    locked_by_calculation: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "mode IN ('month_total', 'daily')",
            name="monthly_input_periods_mode_check",
        ),
        CheckConstraint(
            "baseline_revision >= 1",
            name="monthly_input_periods_revision_positive",
        ),
        UniqueConstraint(
            "tenant_id", "period_key", "baseline_revision",
            name="uq_monthly_input_periods_tenant_period_revision",
        ),
    )


# ── monthly_input_rows (Story 3.1 — Task 2.1) ──────────────────
# One row per user-entered cell. The natural key
# (tenant_id, period_id, stream, product_id, day_no) is enforced by
# a partial unique index in the alembic migration (Postgres treats
# NULL comparisons as NULL, which defeats unique constraints; the
# COALESCE in the index resolves that for ``product_id`` and ``day_no``).
#
# Stream-conditional nullability (PRD §8.M2(b)):
# - orders / production / sales / purchases → product_id NOT NULL,
#   workers/days_per_worker/daily_wage_krw NULL
# - labor → product_id NULL, workers/days_per_worker/daily_wage_krw NOT NULL
# - expenses → product_id NULL (general ledger), money-only fields
#
# Service layer enforces the per-stream shape (Task 4.3 — save_row).
# The DB keeps the column-level NULL permissiveness so the same table
# backs all 6 streams without a UNION ALL of 6 sub-tables.
class MonthlyInputRow(Base):
    __tablename__ = "monthly_input_rows"

    row_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("monthly_input_periods.period_id", ondelete="CASCADE"),
        nullable=False,
    )
    stream: Mapped[str] = mapped_column(Text, nullable=False)
    product_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=True,
    )
    day_no: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # AD-8: qty is small-decimal (NUMERIC 18,4). Engine multiplies with
    # KRW unit_price → result rounded at the service boundary.
    qty: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=18, scale=4), nullable=True
    )
    unit_price_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    amount_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    workers: Mapped[int | None] = mapped_column(Integer, nullable=True)
    days_per_worker: Mapped[int | None] = mapped_column(Integer, nullable=True)
    daily_wage_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    memo: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        CheckConstraint(
            "stream IN ('orders','production','sales','purchases','expenses','labor')",
            name="monthly_input_rows_stream_check",
        ),
        CheckConstraint(
            "day_no IS NULL OR (day_no BETWEEN 1 AND 31)",
            name="monthly_input_rows_day_no_range_check",
        ),
        CheckConstraint(
            "qty IS NULL OR qty >= 0",
            name="monthly_input_rows_qty_nonneg",
        ),
        CheckConstraint(
            "unit_price_krw IS NULL OR unit_price_krw >= 0",
            name="monthly_input_rows_unit_price_nonneg",
        ),
        CheckConstraint(
            "amount_krw IS NULL OR amount_krw >= 0",
            name="monthly_input_rows_amount_nonneg",
        ),
        CheckConstraint(
            "workers IS NULL OR workers >= 0",
            name="monthly_input_rows_workers_nonneg",
        ),
        CheckConstraint(
            "days_per_worker IS NULL OR days_per_worker >= 0",
            name="monthly_input_rows_days_per_worker_nonneg",
        ),
        CheckConstraint(
            "daily_wage_krw IS NULL OR daily_wage_krw >= 0",
            name="monthly_input_rows_daily_wage_nonneg",
        ),
        CheckConstraint(
            "memo IS NULL OR length(memo) <= 500",
            name="monthly_input_rows_memo_length_check",
        ),
    )
