"""apps.api.core.db_models — SQLAlchemy 2.0 ORM models (Story 0.2 + 1.3 + 2.1 + 2.2 + 3.1 + 4.2 + 4.3 + 5.2 + 11.2 + 12.1 + 12.4 + 12.2).

Mapped tables:
- 0001: tenants, users, tenant_memberships, tenant_settings, audit_logs
- 0005 (Story 1.3): uploaded_documents, input_drafts
- 0006 (Story 2.1): products
- 0007 (Story 2.2): bom_lines
- 0009 (Story 3.1): monthly_input_periods, monthly_input_rows
- 0012 (Story 4.2): fiscal_period_snapshots, calc_log
- 0013 (Story 4.3): verification_log
- 0015 (Story 5.2): inventory_ledger (AD-2 append-only)
- 0020 (Story 11.2): fiscal_periods (AD-6 close lock + 4-stage state)
- 0022 (Story 12.1): users totp_* columns (2FA mandatory gate)
- 0023 (Story 12.4): used_challenge_tokens (2FA challenge token replay guard)
- 0024 (Story 12.2): tenant_backups (daily auto-backup + JSON self-download)

Per AD-1/AD-11: this module is in `apps/api/` (infra layer). It does NOT
import `packages.cost_engine` directly. Modules write through services.

Per AD-15: snake_case column names; UUID v4 for `tenant_id` (derived from
JWT, never from request body); UUID v7 for new business entities
(`document_id`, `draft_id`, `id` of `products`, `id` of `bom_lines`) —
generated by `packages.common.uuid7`.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.ext.mutable import MutableList
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from packages.common.uuid7 import uuid7 as _uuid7


class Base(DeclarativeBase):
    """Common ORM base for all apps/api models."""


# ── tenants ────────────────────────────────────────────────
class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    industry: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Story 12.3 — Account Deletion (epics.md §F12.3 + NFR4 2절 + AD-9 Seoul)
    # status FSM: 'active' | 'pending_deletion' | 'deleted'
    # CHECK constraint enforces 3-value enum at DB layer.
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="active")
    deletion_requested_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    deletion_requested_by_user_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    deletion_consent_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("deletion_consents.consent_id", ondelete="SET NULL"),
        nullable=True,
    )
    deletion_scheduled_for: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    deletion_anonymized_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        CheckConstraint(
            "industry IN ('manufacturing', 'manufacturing_retail', 'service', 'mixed')",
            name="tenants_industry_check",
        ),
        CheckConstraint(
            "status IN ('active', 'pending_deletion', 'deleted')",
            name="tenants_status_check",
        ),
    )


# ── users ──────────────────────────────────────────────────
class User(Base):
    __tablename__ = "users"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    # tenant_id is NULLABLE for cross-tenant users (e.g. consultant_proxy
    # before they join a tenant). RLS policy filters to current tenant when
    # tenant_id IS NOT NULL.
    tenant_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=True,
    )
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    twofa_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Story 12.1 (Epic 12 cj-style 1번째) — 2FA mandatory gate (PRD §F12.1).
    # NFR6 AES-256-GCM column-level encryption: totp_secret ciphertext (nonce+ct+tag).
    # NFR5 TLS in transit (service layer does NOT log plaintext).
    # totp_recovery_codes_hash: 8 entries {salt, hash, used_at} (PBKDF2-HMAC-SHA256 hash).
    totp_secret: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    totp_enabled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    totp_failed_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    totp_lockout_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Story 12.4 review P-04 — wrapped in MutableList.as_mutable so
    # SQLAlchemy tracks in-place mutations (consume_recovery_code marks
    # `used_at` on a dict element). Without MutableList, the `__eq__`
    # check sees the same list object and silently skips the UPDATE,
    # allowing the same recovery code to be reused. Type is `list | None`
    # (each entry is `{salt, hash, used_at}` dict, but the column itself
    # is a JSON array — see totp.py service code).
    totp_recovery_codes_hash: Mapped[list | None] = mapped_column(
        MutableList.as_mutable(JSONB), nullable=True
    )

    __table_args__ = (
        CheckConstraint(
            "role IN ('owner', 'member', 'viewer', 'consultant_proxy')",
            name="users_role_check",
        ),
    )


# ── tenant_memberships ─────────────────────────────────────
class TenantMembership(Base):
    __tablename__ = "tenant_memberships"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    joined_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        UniqueConstraint("tenant_id", "user_id", name="tenant_memberships_tenant_user_key"),
    )


# ── tenant_settings (AD-23) ───────────────────────────────
class TenantSettings(Base):
    __tablename__ = "tenant_settings"

    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        primary_key=True,
    )
    settings_version: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=1
    )  # F-17: BigInteger to prevent int4 overflow on long-lived tenants
    onboarding: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    baseline: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    abc: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    ai: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    # Story 3.2 — PRD §6.1 인건비 override (per-tenant payroll policy).
    # Empty dict `{}` means "use `DEFAULT_PAYROLL`" — service layer
    # applies per-field fallback via
    # `packages.services.m2_input.labor_conversion.merge_payroll_settings`.
    payroll: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── audit_logs (AD-2) ─────────────────────────────────────
class AuditLog(Base):
    __tablename__ = "audit_logs"

    # Walking Skeleton (2026-08-16): the DB column has
    # `DEFAULT gen_random_uuid()` (alembic 0001:122) but the model previously
    # declared no `default` and no `server_default`. SQLAlchemy then treats
    # the PK as application-managed and rejects unflushed INSERTs with
    # `FlushError: Instance <AuditLog> has a NULL identity key`. The Python
    # `default=uuid.uuid4` keeps the model honest end-to-end without
    # requiring the app to set the id explicitly.
    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="SET NULL"),
        nullable=True,
    )
    actor_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    target_table: Mapped[str] = mapped_column(Text, nullable=False)
    target_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── used_challenge_tokens (Story 12.4 — 2FA challenge token replay guard) ──
# Records every consumed 2FA challenge token's `jti` (JWT ID) so a captured
# or replayed token cannot be used twice. INSERT with `jti` as PK; duplicate
# key raises IntegrityError → ChallengeTokenAlreadyConsumedError → 401.
# GC: DELETE WHERE used_at < now() - interval '1 hour' (TTL=5min + safety).
class UsedChallengeToken(Base):
    __tablename__ = "used_challenge_tokens"

    jti: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    tenant_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    used_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── uploaded_documents (Story 1.3 — Task 1.2) ───────────────
# One row per uploaded file (PDF / image). Carries the Supabase Storage
# path + sha256 of the bytes (for the `409 DOCUMENT_ALREADY_EXISTS`
# re-upload guard) + retention metadata.
#
# AD-15: document_id is UUID v7 (time-ordered) — better B-tree locality
# for the dashboard's newest-first query. Default is the stdlib helper
# `packages.common.uuid7.uuid7()` so the application never needs to
# remember to set it.
class UploadedDocument(Base):
    __tablename__ = "uploaded_documents"

    document_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    storage_path: Mapped[str] = mapped_column(Text, nullable=False)
    mime_type: Mapped[str] = mapped_column(Text, nullable=False)
    byte_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content_sha256: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Provider job status — separate from `input_drafts.state` per spec Task 1.2.
    job_status: Mapped[str] = mapped_column(Text, nullable=False, default="queued")
    uploaded_by: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    uploaded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # Story 1.3 — Idempotency-Key header support (Task 3.1 / AC #2).
    # Partial unique index enforces dedupe at the DB layer; non-unique
    # when NULL so clients that omit the header still get a fresh row.
    idempotency_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    error_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message_ko: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "job_status IN ('queued', 'processing', 'completed', 'failed')",
            name="uploaded_documents_job_status_check",
        ),
        CheckConstraint("byte_size > 0", name="uploaded_documents_byte_size_positive"),
    )


# ── input_drafts (Story 1.3 — Task 1.2 / AD-7) ───────────────
# One row per AI-extracted field. AD-7 + AD-7-ai-extraction-table-naming.md
# declare `input_drafts` canonical. ERD §8 `ai_extractions.pending_review`
# / `approved` is superseded — see the AD for the mapping.
#
# State machine: draft → reviewed → superseded (3 states, not 2).
# `promoted` is intentionally absent — that's an AD-17 monthly-input semantic.
class InputDraft(Base):
    __tablename__ = "input_drafts"

    draft_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    document_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("uploaded_documents.document_id", ondelete="CASCADE"),
        nullable=False,
    )
    field_name: Mapped[str] = mapped_column(Text, nullable=False)
    ai_value: Mapped[dict] = mapped_column(JSONB, nullable=False)
    confirmed_value: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # NUMERIC(4,3) — 4 digits total, 3 after the decimal → covers 0.000..9.999
    # with the CHECK constraint restricting to [0, 1]. Use Decimal for AD-8 parity.
    confidence: Mapped[Decimal | None] = mapped_column(Numeric(precision=4, scale=3), nullable=True)
    state: Mapped[str] = mapped_column(Text, nullable=False, default="draft")
    evidence: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    draft_hash: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    requested_by: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reviewed_by: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "state IN ('draft', 'reviewed', 'superseded')",
            name="input_drafts_state_check",
        ),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="input_drafts_confidence_range_check",
        ),
    )


# ── products (Story 2.1 — Tasks 3.1 / 3.2) ──────────────────
# One row per registered product/item. AD-18 single product identity:
# `id` (UUID v7) is the sole key referenced by BOM (Story 2.2),
# inventory ledger (Story 2.2+), and reports (Epic 6).
#
# `code` is a per-tenant per-type sequence (PRD §8.M1) — NOT the primary
# key. Tenants may share codes across tenant boundaries; the unique index
# `(tenant_id, code)` enforces intra-tenant uniqueness.
#
# Money columns are AD-8 strict: KRW = BIGINT (no fractional won), USD =
# NUMERIC(18,2) (2 decimal places, ROUND_HALF_EVEN per chunk-B).
class Product(Base):
    __tablename__ = "products"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    product_type: Mapped[str] = mapped_column(Text, nullable=False)
    code: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    # AD-8: KRW stored as BIGINT (no fractional won). TS uses `bigint`.
    unit_cost_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # AD-8: USD stored as NUMERIC(18,2). Decimal-typed; rounded at the
    # service boundary (ROUND_HALF_EVEN, Story 0.4 chunk-B).
    unit_cost_usd: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=18, scale=2), nullable=True
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Soft-delete flag (AC #5). Hard delete is forbidden (AD-2 append-only).
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "product_type IN ('product', 'semi_product', 'material', 'goods', 'service')",
            name="products_product_type_check",
        ),
        CheckConstraint(
            "length(name) BETWEEN 1 AND 200",
            name="products_name_length_check",
        ),
        CheckConstraint(
            "unit IS NULL OR length(unit) <= 20",
            name="products_unit_length_check",
        ),
        CheckConstraint(
            "unit_cost_krw IS NULL OR unit_cost_krw >= 0",
            name="products_unit_cost_krw_nonneg",
        ),
        CheckConstraint(
            "unit_cost_usd IS NULL OR unit_cost_usd >= 0",
            name="products_unit_cost_usd_nonneg",
        ),
        CheckConstraint(
            "description IS NULL OR length(description) <= 2000",
            name="products_description_length_check",
        ),
        # AC #3 — same-tenant code uniqueness. RLS-scoped (NOT global).
        UniqueConstraint("tenant_id", "code", name="uq_products_tenant_code"),
    )


# ── bom_lines (Story 2.2 — Task 2.2) ────────────────────────────
# One row per (parent_product, child_product) link. AD-18 single product
# identity: both FKs point at `products.id` (UUID v7).
#
# `ratio` is `NUMERIC(7,4)` (AD-8 extended) — 4 decimal places, max
# 100.0000. CHECK `0 < ratio <= 100`. Python `Decimal`. Quantize via
# `ROUND_HALF_EVEN` per Story 0.4 chunk-B.
#
# Append-only-leaning (AD-2): the bulk-replace PUT semantics mean DELETE
# is a service-layer operation, not a per-row endpoint. RLS has no DELETE
# policy; the UNIQUE INDEX is the only duplicate-children defense at the
# DB layer (the service pre-validates for typed 422 responses).
class BOMLine(Base):
    __tablename__ = "bom_lines"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    # AD-18: both FKs to products.id (UUID v7). ON DELETE RESTRICT —
    # hard-deleting a product is forbidden (AD-2); soft-delete preserves
    # BOM history (Story 2.1 AC #5 + Story 2.2 AC #9).
    parent_product_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
    )
    child_product_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
    )
    # AD-8 — ratio is NUMERIC(7,4). Decimal-typed in both Python and TS.
    # `Decimal` is imported above; mapped_column handles the SQL type.
    ratio: Mapped[Decimal] = mapped_column(Numeric(precision=7, scale=4), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "ratio > 0 AND ratio <= 100",
            name="bom_lines_ratio_range_check",
        ),
    )


# ── monthly_input_periods (Story 3.1 — Task 2.1) ──────────────
# One row per (tenant, period_key, baseline_revision) triple.
# AD-23 4-namespace: uniqueness on the triple keeps each tenant's
# periods fully isolated. Multiple revisions of the same period can
# coexist (Epic 4 first_calc bumps `baseline_revision` and keeps the
# previous row for V8 regression comparison).
#
# `mode` carries the F2.1 일자별/월합계 toggle. Switching does NOT
# create a new revision — it's a per-period UI preference (not a
# baseline change). `baseline_revision` only bumps at first_calc time
# (Story 3.4 + Epic 4).
#
# `locked_by_calculation`: AD-13 says MonthInputAdapter reads but
# doesn't lock — Epic 4 M3 calc sets this true so the UI can show
# "마감됨" badge and disable edits. Epic 3.1 only INSERTs with default
# `false`.
class MonthlyInputPeriod(Base):
    __tablename__ = "monthly_input_periods"

    period_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    mode: Mapped[str] = mapped_column(Text, nullable=False, default="month_total")
    baseline_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    locked_by_calculation: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # Story 3.3 (Task 2.2) — per-period per-product opening inventory
    # balance. Consumed by the inventory math kernel
    # (`packages.services.m2_input.inventory_math` — post-A19 home).
    # MVP default `{}` — service layer falls back to 0 for all products.
    # Epic 5 Story 5-1 auto-carries closing balances from the previous
    # period (TODO(epic-5) marker closed in Story 5-2; A19 carry-over
    # sprint removed the legacy `inventory_projection` module).
    opening_inventory: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # Story 6.1 (Task T6.2) — closing period service columns.
    # AD-6 fiscal-period close lock lifecycle:
    #   'open' → 'closing' → 'closed' (1-way state machine).
    # `status` defaults to 'open' (preserves 5-3 wire back-compat).
    # `finalized_at` and `closed_by_actor_id` populated by 6-1
    # confirm_closing_period dispatch.
    # `closing_snapshot_event_count` = number of inventory_ledger
    # rows with event_type='closing_snapshot' inserted at confirm.
    status: Mapped[str] = mapped_column(Text, nullable=False, default="open")
    finalized_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_by_actor_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    closing_snapshot_event_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    __table_args__ = (
        CheckConstraint(
            "mode IN ('month_total', 'daily')",
            name="monthly_input_periods_mode_check",
        ),
        CheckConstraint(
            "baseline_revision >= 1",
            name="monthly_input_periods_revision_positive",
        ),
        # Story 6.1 — AD-6 1-way fiscal-period state machine (open →
        # closing → closed). Alembic 0017 mirrors this CHECK.
        CheckConstraint(
            "status IN ('open', 'closing', 'closed')",
            name="chk_closing_period_status",
        ),
        # Story 6.1 — closing_snapshot_event_count must be ≥ 0
        # (defense-in-depth; service layer also enforces).
        CheckConstraint(
            "closing_snapshot_event_count >= 0",
            name="chk_closing_snapshot_event_count_non_negative",
        ),
        UniqueConstraint(
            "tenant_id",
            "period_key",
            "baseline_revision",
            name="uq_monthly_input_periods_tenant_period_revision",
        ),
    )


# ── monthly_input_rows (Story 3.1 — Task 2.1) ──────────────────
# One row per user-entered cell. The natural key
# (tenant_id, period_id, stream, product_id, day_no) is enforced by
# a partial unique index in the alembic migration (Postgres treats
# NULL comparisons as NULL, which defeats unique constraints; the
# COALESCE in the index resolves that for ``product_id`` and ``day_no``).
#
# Stream-conditional nullability (PRD §8.M2(b)):
# - orders / production / sales / purchases → product_id NOT NULL,
#   workers/days_per_worker/daily_wage_krw NULL
# - labor → product_id NULL, workers/days_per_worker/daily_wage_krw NOT NULL
# - expenses → product_id NULL (general ledger), money-only fields
#
# Service layer enforces the per-stream shape (Task 4.3 — save_row).
# The DB keeps the column-level NULL permissiveness so the same table
# backs all 6 streams without a UNION ALL of 6 sub-tables.
class MonthlyInputRow(Base):
    __tablename__ = "monthly_input_rows"

    row_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("monthly_input_periods.period_id", ondelete="CASCADE"),
        nullable=False,
    )
    stream: Mapped[str] = mapped_column(Text, nullable=False)
    product_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=True,
    )
    day_no: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # AD-8: qty is small-decimal (NUMERIC 18,4). Engine multiplies with
    # KRW unit_price → result rounded at the service boundary.
    qty: Mapped[Decimal | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    unit_price_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    amount_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    workers: Mapped[int | None] = mapped_column(Integer, nullable=True)
    days_per_worker: Mapped[int | None] = mapped_column(Integer, nullable=True)
    daily_wage_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    memo: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Story 3.2 FTE precision (PRD §6.1 인건비 구성) ──────────
    # Nullable across all 6 streams — service layer enforces non-NULL
    # only when stream == 'labor' (`_validate_labor_shape`).
    pay_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    monthly_salary_basis_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    overtime_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    welfare_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    bonus_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    retirement_reserve_krw: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # 4대보험·퇴직 회사부담 비율 — AD-8 NUMERIC(5,4) (4 decimal places)
    company_burden_rate: Mapped[Decimal | None] = mapped_column(
        Numeric(precision=5, scale=4), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "stream IN ('orders','production','sales','purchases','expenses','labor')",
            name="monthly_input_rows_stream_check",
        ),
        CheckConstraint(
            "day_no IS NULL OR (day_no BETWEEN 1 AND 31)",
            name="monthly_input_rows_day_no_range_check",
        ),
        CheckConstraint(
            "qty IS NULL OR qty >= 0",
            name="monthly_input_rows_qty_nonneg",
        ),
        CheckConstraint(
            "unit_price_krw IS NULL OR unit_price_krw >= 0",
            name="monthly_input_rows_unit_price_nonneg",
        ),
        CheckConstraint(
            "amount_krw IS NULL OR amount_krw >= 0",
            name="monthly_input_rows_amount_nonneg",
        ),
        CheckConstraint(
            "workers IS NULL OR workers >= 0",
            name="monthly_input_rows_workers_nonneg",
        ),
        CheckConstraint(
            "days_per_worker IS NULL OR days_per_worker >= 0",
            name="monthly_input_rows_days_per_worker_nonneg",
        ),
        CheckConstraint(
            "daily_wage_krw IS NULL OR daily_wage_krw >= 0",
            name="monthly_input_rows_daily_wage_nonneg",
        ),
        CheckConstraint(
            "memo IS NULL OR length(memo) <= 500",
            name="monthly_input_rows_memo_length_check",
        ),
        # ── Story 3.2 labor precision CHECK constraints ─────────
        # pay_type is a discriminator so we keep it string-typed at the DB
        # layer (matches the unique-check on stream with the same style).
        CheckConstraint(
            "pay_type IS NULL OR pay_type IN ('monthly', 'daily')",
            name="monthly_input_rows_pay_type_check",
        ),
        CheckConstraint(
            "monthly_salary_basis_krw IS NULL OR monthly_salary_basis_krw >= 0",
            name="monthly_input_rows_monthly_salary_basis_nonneg",
        ),
        CheckConstraint(
            "overtime_krw IS NULL OR overtime_krw >= 0",
            name="monthly_input_rows_overtime_nonneg",
        ),
        CheckConstraint(
            "welfare_krw IS NULL OR welfare_krw >= 0",
            name="monthly_input_rows_welfare_nonneg",
        ),
        CheckConstraint(
            "bonus_krw IS NULL OR bonus_krw >= 0",
            name="monthly_input_rows_bonus_nonneg",
        ),
        CheckConstraint(
            "retirement_reserve_krw IS NULL OR retirement_reserve_krw >= 0",
            name="monthly_input_rows_retirement_reserve_nonneg",
        ),
        # NUMERIC(5,4) → CHECK [0, 1] (4 decimal places enough for
        # 0.0000 to 9.9999, restricted to 0..1 by CHALLENGE).
        CheckConstraint(
            "company_burden_rate IS NULL "
            "OR (company_burden_rate >= 0 AND company_burden_rate <= 1)",
            name="monthly_input_rows_company_burden_rate_range",
        ),
    )


# ── monthly_input_promotions (Story 10.4 — T3 ORM mirror) ───────
# AD-17 verbatim InputPromoter.promote() idempotency ledger.
# Schema:
#   - promotion_id        UUID PK DEFAULT gen_random_uuid()
#   - tenant_id           UUID NOT NULL FK → tenants(id) ON DELETE RESTRICT
#   - period_key          VARCHAR(32) NOT NULL (master PRD §V4)
#   - source_draft_id     UUID NOT NULL FK → input_drafts(draft_id)
#                         ON DELETE RESTRICT
#   - monthly_input_row_id UUID NULL FK → monthly_input_rows(id)
#                         ON DELETE SET NULL
#   - idempotency_key     UUID NOT NULL (UUID v5 derivation from kernel)
#   - promoted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
# UNIQUE constraint `uq_monthly_input_promotions_tenant_period_draft`
# ON (tenant_id, period_key, source_draft_id) — DB-level idempotency
# (alembic 0032 wire). INSERT-only trigger
# `trg_monthly_input_promotions_insert_only` enforces AD-2
# append-only invariant.
class MonthlyInputPromotion(Base):
    __tablename__ = "monthly_input_promotions"

    promotion_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    source_draft_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("input_drafts.draft_id", ondelete="RESTRICT"),
        nullable=False,
    )
    monthly_input_row_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("monthly_input_rows.row_id", ondelete="SET NULL"),
        nullable=True,
    )
    idempotency_key: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    promoted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "period_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'",
            name="monthly_input_promotions_period_key_format",
        ),
    )


# ── fiscal_period_snapshots (Story 4.2 — Task 1.4) ────────────
# Append-only-leaning ledger (AD-22) of per-tenant per-period calculation
# results. M3 module is the only writer (services/calc_orchestrator.py).
# State field tracks verified → committed (M11, Epic 11) → reversed (Epic 11
# Story 11-3). `engine_type='trad'` is the default — Epic 9 Story 9-2 will
# INSERT 'abc' rows for ABC costing.
#
# Idempotency (AC #4): the UNIQUE constraint on
# (tenant_id, period_key, baseline_revision, engine_type) guarantees
# one snapshot per (tenant, period, baseline, engine). Re-INSERT attempt
# raises `IntegrityError` which the orchestrator catches + checks
# result_hash for the same-hash idempotent skip path.
#
# AD-8: KRW fields are `BIGINT` (1원 precision). Engine's `result_hash`
# is 64-char hex SHA-256 (EP-IC-1).
class FiscalPeriodSnapshot(Base):
    __tablename__ = "fiscal_period_snapshots"

    snapshot_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    baseline_revision: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    engine_type: Mapped[str] = mapped_column(Text, nullable=False, default="trad")
    material_cost: Mapped[int] = mapped_column(BigInteger, nullable=False)
    labor_cost: Mapped[int] = mapped_column(BigInteger, nullable=False)
    overhead_cost: Mapped[int] = mapped_column(BigInteger, nullable=False)
    manufacturing_cost: Mapped[int] = mapped_column(BigInteger, nullable=False)
    inventory_adjustment: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    result_hash: Mapped[str] = mapped_column(Text, nullable=False)
    state: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # ── Story 9.3 (T3 prep) — ABC dual-route JSONB subdocuments ───
    # cost_object_breakdown: per-product ABC allocation rows (PRD §F9.3 +
    # A29 forward-lock). NULL for engine_type='trad' (manufacturing-kind
    # traditional costing). NFR18 lock on column semantics.
    cost_object_breakdown: Mapped[list | None] = mapped_column(
        MutableList.as_mutable(JSONB), nullable=True
    )
    # unused_capacity_breakdown: per-department unused capacity rows
    # (PRD §A9 + §V7). NULL for engine_type='trad'. NFR18 lock.
    unused_capacity_breakdown: Mapped[list | None] = mapped_column(
        MutableList.as_mutable(JSONB), nullable=True
    )

    __table_args__ = (
        CheckConstraint(
            "state IN ('verified', 'committed', 'reversed')",
            name="fiscal_period_snapshots_state_check",
        ),
        CheckConstraint(
            "baseline_revision >= 1",
            name="fiscal_period_snapshots_revision_positive",
        ),
        UniqueConstraint(
            "tenant_id",
            "period_key",
            "baseline_revision",
            "engine_type",
            name="uq_fiscal_period_snapshots_tenant_period_revision_engine",
        ),
    )


# ── calc_log (Story 4.2 — Task 1.4) ───────────────────────────
# Audit-first ledger (CR 1.1 lesson) for the M3 calculation flow. Written
# BEFORE fiscal_period_snapshots INSERT in the same REPEATABLE READ
# transaction. `action` discriminates: `compute` (first write),
# `idempotent_skip` (same-hash re-call), `rollback` (engine error →
# ROLLBACK). `result_hash` is nullable because `rollback` may fire
# before the engine produces a stable hash.
class CalcLog(Base):
    __tablename__ = "calc_log"

    calc_log_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    baseline_revision: Mapped[int] = mapped_column(Integer, nullable=False)
    engine_type: Mapped[str] = mapped_column(Text, nullable=False, default="trad")
    action: Mapped[str] = mapped_column(Text, nullable=False)
    result_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "action IN ('compute', 'idempotent_skip', 'rollback')",
            name="calc_log_action_check",
        ),
        CheckConstraint(
            "baseline_revision >= 1",
            name="calc_log_revision_positive",
        ),
    )


# ── verification_log (Story 4.3 — Task 4.1) ───────────────────
# AD-12 verification-first audit ledger. Written by
# `CalcOrchestrator._write_verification_log` in the same REPEATABLE READ
# transaction as `calc_log` (audit-first, CR 1.1 lesson) and BEFORE
# `fiscal_period_snapshots` INSERT.
#
# Note: `top_failure_code` and `top_failure_message_ko` are populated
# only for `action='verification_failed'` (the AD-12 first-failed rule).
# For `action='verification_passed'`, both fields are NULL.
#
# The CHECK constraint defines the 3-value enum that the
# `apps/api/core/audit_action.py` registry (ActionClass.VERIFICATION_LOG)
# validates against in production writes. Phase 4 drift detector will
# enforce 3-way consistency (registry vs DB CHECK vs call sites).
class VerificationLog(Base):
    __tablename__ = "verification_log"

    verification_log_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    baseline_revision: Mapped[int] = mapped_column(Integer, nullable=False)
    action: Mapped[str] = mapped_column(Text, nullable=False)
    top_failure_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    top_failure_message_ko: Mapped[str | None] = mapped_column(Text, nullable=True)
    result_hash: Mapped[str] = mapped_column(Text, nullable=False)
    trace_id: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        CheckConstraint(
            "action IN ('verification_passed', 'verification_failed', 'verification_skipped')",
            name="verification_log_action_check",
        ),
        CheckConstraint(
            "baseline_revision >= 1",
            name="verification_log_revision_positive",
        ),
    )


# ── inventory_ledger (Story 5.2 — Task 5) ──────────────────────
# AD-2 append-only ledger (PRD §6.2 수불부). INSERT-only at the DB
# layer via a `BEFORE UPDATE OR DELETE` row-level trigger that raises
# custom SQLSTATE `P0001` with a Korean message. Corrections flow
# through AD-22 reversal sequence (Epic 11 module authority insert).
#
# AD-18 single product identity: `product_id` FK to `products.id`
# (UUID v7). AD-4 RLS: `tenant_id` FK to `tenants.id`.
#
# AD-8 monetary types: `qty` is NUMERIC(18,4) NULLABLE (OQ2 cj-style
# default — non-quantitative events like `closing_snapshot` may have
# NULL qty). AD-22 reversal fields (`reverses_event_id` +
# `correction_group_id`) are populated only by reversal rows.
#
# AD-15: snake_case column names. UUID v7 default for `event_id`
# (mirrors `packages.services.m4_inventory.ledger.InventoryLedgerEvent`).
#
# Drift detector: 11-value event_type CHECK constraint mirrors
# `packages.services.m4_inventory.ledger.INVENTORY_LEDGER_EVENT_TYPES`
# + `apps.api.core.audit_action._REGISTRY[ActionClass.INVENTORY_LEDGER]`.
# Tests: `tests/integration/test_audit_action_consistency.py`.
class InventoryLedger(Base):
    __tablename__ = "inventory_ledger"

    event_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    product_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    # AD-8 / OQ2: NUMERIC(18,4) NULLABLE for non-quantitative events.
    qty: Mapped[Decimal | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    trace_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), nullable=False)
    # AD-22 reversal sequence (Epic 11 forward-fill).
    reverses_event_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    correction_group_id: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), nullable=True)
    # AD-22 reversal_of_period_key — original event's period_key (may differ
    # from period_key if corrected row crosses periods). Added in Alembic 0019.
    reversal_of_period_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    inserted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        # 11-value event_type CHECK (OQ3 cj-style default).
        CheckConstraint(
            "event_type IN ("
            "'opening_carried', "
            "'opening_carried_stale_overwrite', "
            "'purchase_inbound', "
            "'sales_outbound', "
            "'production_output_inbound', "
            "'production_material_consumption', "
            "'adjustment_positive', "
            "'adjustment_negative', "
            "'reversal_negating', "
            "'reversal_corrected', "
            "'closing_snapshot'"
            ")",
            name="inventory_ledger_event_type_check",
        ),
        # AD-24 typed period_key: 'YYYY-MM'.
        CheckConstraint(
            "period_key ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name="inventory_ledger_period_key_format_check",
        ),
        # qty nonneg when present (NULL allowed for non-quantitative events).
        CheckConstraint(
            "qty IS NULL OR qty >= 0",
            name="inventory_ledger_qty_nonneg_when_present",
        ),
        # Quantitative events MUST have non-NULL qty.
        CheckConstraint(
            "event_type = 'closing_snapshot' OR qty IS NOT NULL",
            name="inventory_ledger_qty_required_for_quantitative_events",
        ),
    )


# ── fiscal_periods (Story 11.2 — AD-6 close lock + 4-stage state) ─
# Greenfield table introduced in Alembic 0020. One row per
# (tenant_id, period_key) — 1 fiscal period per tenant per month. Tracks:
#   - `status`: 1-way state machine (open → closing → closed → reversed)
#     AD-6 final is `closed`. Reopen requires operator action (W2 deferral).
#   - `close_sequence_state`: 4-stage verification
#     (divisions → manufacturing → abc → common → confirmed). PRD §F11.1.
#   - 4 step-completion timestamps (divisions_/manufacturing_/abc_/
#     common_completed_at) — defense-in-depth CHECK constraints enforce
#     chronological ordering at the DB level (mirrors
#     `close_sequence_order.py` pure-kernel invariants).
#   - `close_sequence_blocked_reason_ko`: Korean message when partial
#     close guard rejects confirm_close_sequence (AD-15 §11 SSOT).
#   - `closed_at` + `closed_by_actor_id`: status='closed' transition
#     audit trail.
# RLS policy: supabase/policies/0011_fiscal_periods_rls.sql (4-policy
# split — delete BLOCKED for AD-6 close lock).
class FiscalPeriod(Base):
    __tablename__ = "fiscal_periods"

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    # AD-6 1-way state machine. Reopen requires operator action (W2).
    status: Mapped[str] = mapped_column(Text, nullable=False, default="open")
    divisions_completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    manufacturing_completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    abc_completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    common_completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # 4-stage verification state (PRD §F11.1).
    close_sequence_state: Mapped[str] = mapped_column(Text, nullable=False, default="divisions")
    close_sequence_blocked_reason_ko: Mapped[str | None] = mapped_column(Text, nullable=True)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_by_actor_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (
        # AD-24 typed period_key: 'YYYY-MM'.
        CheckConstraint(
            "period_key ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name="fiscal_periods_period_key_format_check",
        ),
        CheckConstraint(
            "status IN ('open', 'closing', 'closed', 'reversed')",
            name="fiscal_periods_status_check",
        ),
        CheckConstraint(
            "close_sequence_state IN "
            "('divisions', 'manufacturing', 'abc', 'common', 'confirmed')",
            name="fiscal_periods_close_sequence_state_check",
        ),
        # Defense-in-depth stage ordering (mirror close_sequence_order.py).
        CheckConstraint(
            "divisions_completed_at IS NOT NULL " "OR manufacturing_completed_at IS NULL",
            name="fiscal_periods_divisions_ordering_check",
        ),
        CheckConstraint(
            "manufacturing_completed_at IS NOT NULL " "OR abc_completed_at IS NULL",
            name="fiscal_periods_manufacturing_ordering_check",
        ),
        CheckConstraint(
            "abc_completed_at IS NOT NULL " "OR common_completed_at IS NULL",
            name="fiscal_periods_abc_ordering_check",
        ),
        # close_sequence_state='confirmed' requires status='closed'.
        CheckConstraint(
            "close_sequence_state != 'confirmed' OR status = 'closed'",
            name="fiscal_periods_confirmed_requires_closed_check",
        ),
        # status='closed' requires closed_at populated.
        CheckConstraint(
            "status != 'closed' OR closed_at IS NOT NULL",
            name="fiscal_periods_closed_requires_closed_at_check",
        ),
        UniqueConstraint(
            "tenant_id",
            "period_key",
            name="fiscal_periods_tenant_period_unique",
        ),
    )


# ── deletion_consents (Story 12.3) ──────────────────────────
# One row per deletion consent record. AES-256-GCM encrypted consent
# text (NFR6 invariant — distinct AAD `b"deletion_consent"` per column).
# AD-2 INSERT-only enforced via RLS policy in `0015_tenants_deletion_rls.sql`
# (UPDATE / DELETE forbidden at row level).
#
# Plaintext consent text is NEVER stored — only the SHA-256 hex digest
# (`consent_text_hash`) is retained for audit trace.
#
# `consent_id` is UUID v4 (AD-15 §6 — supersedes UUID v7 for tenant_id
# lineage; consent rows are NOT time-ordered by nature).
class DeletionConsent(Base):
    __tablename__ = "deletion_consents"

    consent_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    # SHA-256 hex digest of plaintext consent text (audit trace).
    consent_text_hash: Mapped[str] = mapped_column(Text, nullable=False)
    # AES-256-GCM ciphertext (28-byte overhead = 12-byte nonce + ciphertext + 16-byte tag).
    encrypted_consent_text: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    consent_checked_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    consent_checked_by_user_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    consent_ip: Mapped[str | None] = mapped_column(Text, nullable=True)
    consent_user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "length(consent_text_hash) = 64",
            name="deletion_consents_hash_length_check",
        ),
    )


# ── tenant_backups (Story 12.2 — daily auto-backup + JSON self-download) ──
# AD-2 INSERT-only (BEFORE UPDATE OR DELETE trigger raises
# `append-only violation` per migration 0024 — audit_logs 0001 pattern).
# Soft-delete via `purged_at` column for 30-day retention sweep.
#
# Why Postgres JSONB (not Supabase Storage)? Per AC #2:
# - Storage target = Postgres table `tenant_backups` JSONB column.
# - AD-9 Seoul: Supabase Seoul Postgres = ap-northeast-2 = qualifies.
# - 의존성 0 (no Storage SDK bump per 12-5 QR manual-entry decision).
# - STACK_PIN.yaml 변경 0건.
#
# Schema (12 columns):
# - backup_id UUID PK (uuid4, AD-15 §3 identity)
# - tenant_id UUID FK → tenants.id (CASCADE)
# - backup_date DATE (KST date — KST 02:00 cron)
# - created_at TIMESTAMPTZ (UTC timestamp)
# - schema_version VARCHAR(16) (envelope top-level, AC #8 — versioning)
# - payload JSONB (7-table dump — see packages/services/m12_account/backup_export.py)
# - payload_sha256 CHAR(64) (deterministic digest)
# - row_count_total INTEGER (sum of 7 table counts)
# - audit_log_exported_rows INTEGER (audit_logs count after 365d collapse)
# - retention_class VARCHAR(16) ('daily' / 'quarterly' honestly DEFER)
# - purged_at TIMESTAMPTZ NULL (30-day soft-delete marker)
# - triggered_by_user_id UUID FK → users.id SET NULL (manual trigger trace)
class TenantBackup(Base):
    __tablename__ = "tenant_backups"

    backup_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    backup_date: Mapped[datetime] = mapped_column(DateTime(timezone=False), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    schema_version: Mapped[str] = mapped_column(Text, nullable=False, default="1.0")
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    payload_sha256: Mapped[str] = mapped_column(Text, nullable=False)
    row_count_total: Mapped[int] = mapped_column(Integer, nullable=False)
    audit_log_exported_rows: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    retention_class: Mapped[str] = mapped_column(Text, nullable=False, default="daily")
    purged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    triggered_by_user_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )


# ─────────────────────────────────────────────────────────────
# Story 8.1 — Budget Scenario (PRD §F8.1 + AD-24 virtual period key)
#
# budget_scenarios table (Alembic 0026):
#   - id UUID v7 PK
#   - tenant_id UUID NOT NULL FK → tenants(id) ON DELETE CASCADE
#   - period_key TEXT NOT NULL CHECK (virtual `YYYY-MM#B<n>` pattern)
#   - real_period_key TEXT NOT NULL CHECK (real `YYYY-MM` pattern)
#   - scenario_index INT NOT NULL CHECK (>= 1)
#   - scenario_hash TEXT NOT NULL (V8 determinism, sha256 digest)
#   - created_by UUID NOT NULL FK → users(id)
#   - created_at_kst TIMESTAMPTZ NOT NULL DEFAULT NOW() (AD-9 Seoul)
# UNIQUE(tenant_id, period_key) — duplicate period_key 방지
# UNIQUE(tenant_id, real_period_key) — 1차 MVP scenario 1개 잠금 DB-level guard
#   (validate_scenario_uniqueness + DB UNIQUE 제약 defense-in-depth).
# ─────────────────────────────────────────────────────────────
class BudgetScenario(Base):
    __tablename__ = "budget_scenarios"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id",
            "period_key",
            name="uq_budget_scenarios_tenant_id_period_key",
        ),
        UniqueConstraint(
            "tenant_id",
            "real_period_key",
            name="uq_budget_scenarios_tenant_id_real_period_key",
        ),
        CheckConstraint(
            "period_key ~ '^\\d{4}-(0[1-9]|1[0-2])#B[1-9]\\d*$'",
            name="ck_budget_scenarios_period_key_pattern",
        ),
        CheckConstraint(
            "real_period_key ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name="ck_budget_scenarios_real_period_key_pattern",
        ),
        CheckConstraint(
            "scenario_index >= 1",
            name="ck_budget_scenarios_scenario_index_positive",
        ),
        Index(
            "idx_budget_scenarios_tenant_id_period_key",
            "tenant_id",
            "period_key",
        ),
    )

    id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    real_period_key: Mapped[str] = mapped_column(Text, nullable=False)
    scenario_index: Mapped[int] = mapped_column(Integer, nullable=False)
    scenario_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_by: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
    )
    created_at_kst: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── ai_insight_cache (Story 10.2, alembic 0030) ─────────────
class AiInsightCache(Base):
    """AD-25 verbatim 3-tuple AI insight cache row (master PRD §F10.1).

    cache key = (tenant_id, period_key, calculation_result_hash) + per-kind row.
    Per (tenant, period, kind, hash) UNIQUE constraint (idempotent INSERT).
    INSERT-only by AD-2 — UPDATE/DELETE blocked by trigger (audit-first guard).

    10-2 wire 진입 시점에 all 3 rows per cache entry are `source_kind='auto_analysis'`.
    `source_kind='ai_reference'` 항목 추가는 Story 10.3 wire 진입 시점에 detailed wire
    (AD-7 verbatim, 10-3 badge separation forward-bind).
    """

    __tablename__ = "ai_insight_cache"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id",
            "period_key",
            "insight_kind",
            "calculation_result_hash",
            name="uq_ai_insight_cache_tenant_period_kind_hash",
        ),
        CheckConstraint(
            "insight_kind IN ('cost_reduction_candidate', 'anomaly_pattern', 'forecast')",
            name="ck_ai_insight_cache_insight_kind",
        ),
        CheckConstraint(
            "source_kind IN ('auto_analysis', 'ai_reference')",
            name="ck_ai_insight_cache_source_kind",
        ),
        CheckConstraint(
            "period_key ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name="ck_ai_insight_cache_period_key_format",
        ),
        Index(
            "idx_ai_insight_cache_tenant_period",
            "tenant_id",
            "period_key",
        ),
        Index(
            "idx_ai_insight_cache_calculation_hash",
            "calculation_result_hash",
        ),
        Index(
            "idx_ai_insight_cache_published_at_desc",
            "tenant_id",
            "generated_at",
        ),
    )

    insight_cache_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=_uuid7
    )
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    calculation_result_hash: Mapped[str] = mapped_column(Text, nullable=False)
    insight_kind: Mapped[str] = mapped_column(Text, nullable=False)
    source_kind: Mapped[str] = mapped_column(Text, nullable=False)
    question: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    evidence_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class AiInsightComment(Base):
    """AD-7 + AD-25 verbatim AI insight comment row (master PRD §F10.2).

    Story 10.3 (cj-style Epic 10 4번째 진입점, cj-style 30번째 epic 연속).

    cache key = (tenant_id, period_key, calculation_result_hash) + per-kind row.
    Per (tenant, period, kind, hash) UNIQUE constraint (idempotent INSERT).
    INSERT-only by AD-2 — UPDATE/DELETE blocked by trigger (F10.2-(c)
    `auto_analysis` 의견 read-only + audit-first guard).

    `source_kind` discriminator (AD-7 verbatim, 10-2 kernel SSOT 보존):
      - 'auto_analysis' → 파란 배지 '📊 자동 분석'
                          + tooltip '이 의견은 고정 템플릿입니다'
      - 'ai_reference'  → 보라 배지 '🤖 AI 참고(검증 필요)'
                          + tooltip 'AI는 비권위적입니다 — 확정 책임은 사용자에게'
    """

    __tablename__ = "ai_insight_comments"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id",
            "period_key",
            "comment_kind",
            "calculation_result_hash",
            name="uq_ai_insight_comments_tenant_period_kind_hash",
        ),
        CheckConstraint(
            "comment_kind IN ('cost_reduction_candidate', 'anomaly_pattern', "
            "'forecast', 'risk_warning', 'industry_benchmark')",
            name="ck_ai_insight_comments_comment_kind",
        ),
        CheckConstraint(
            "source_kind IN ('auto_analysis', 'ai_reference')",
            name="ck_ai_insight_comments_source_kind",
        ),
        CheckConstraint(
            "period_key ~ '^\\d{4}-(0[1-9]|1[0-2])$'",
            name="ck_ai_insight_comments_period_key_format",
        ),
        Index(
            "idx_ai_insight_comments_tenant_period",
            "tenant_id",
            "period_key",
        ),
        Index(
            "idx_ai_insight_comments_calculation_hash",
            "calculation_result_hash",
        ),
        Index(
            "idx_ai_insight_comments_source_kind",
            "tenant_id",
            "source_kind",
        ),
    )

    comment_id: Mapped[UUID] = mapped_column(PgUUID(as_uuid=True), primary_key=True, default=_uuid7)
    tenant_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    period_key: Mapped[str] = mapped_column(Text, nullable=False)
    calculation_result_hash: Mapped[str] = mapped_column(Text, nullable=False)
    comment_kind: Mapped[str] = mapped_column(Text, nullable=False)
    source_kind: Mapped[str] = mapped_column(Text, nullable=False)
    body_text: Mapped[str] = mapped_column(Text, nullable=False)
    evidence_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
