"""packages.services.m7_simulation.projection_pdf_helpers — Story 7.2 PDF envelope helpers.

Thin wrapper around Epic 6 M5 PDF generator for the projection envelope
(M5 §9 #20+ "원가 예측 보고서" envelope format).

READ-ONLY envelope (CR 1.1 AD-2 audit-skip for read-only operations):
- No DB writes
- No audit emit (simulation is read-only)
- PDF generated by delegating to `packages.services.m6_reports.pdf_helpers`
  (Epic 6 M5 reuse pattern).

AD-11 layer rule: this module is a thin wrapper around the M5 PDF generator
+ projection envelope serialization. The actual PDF byte generation
happens via `packages.services.m6_reports.pdf_helpers:generate_pdf_from_envelope`.

CR 11-3 D-2 ALLOWED_SERVICE_SUBMODULES sweep — `m7_simulation.projection_pdf_helpers`
registered in `tests/architecture/test_api_calls_only_ports.py` (T4 wire).
"""

from __future__ import annotations

from datetime import UTC, datetime

from packages.cost_engine.cvp import CVPBaseline
from packages.cost_engine.projection import (
    NextMonthProjection,
    ProjectionInputs,
)

# ── Constants ────────────────────────────────────────────────
PROJECTION_PDF_REPORT_CODE: str = "COST_PREDICTION"
PROJECTION_PDF_TITLE_KO: str = "원가 예측 보고서"


# ── Envelope serializer ─────────────────────────────────────
def serialize_projection_pdf_envelope(
    *,
    baseline: CVPBaseline,
    projection_inputs: ProjectionInputs,
    projection: NextMonthProjection,
    period_key: str,
    projection_month: str,
    generated_at_kst: str | None = None,
) -> dict[str, object]:
    """Build the projection PDF envelope (M5 §9 #20+ format).

    Args:
        baseline: CVPBaseline (snapshot-extracted)
        projection_inputs: 4종 파라미터 user inputs
        projection: NextMonthProjection result
        period_key: AD-24 YYYY-MM (baseline source period)
        projection_month: AD-24 YYYY-MM (projection target month)
        generated_at_kst: ISO 8601 KST timestamp (optional, defaults to now UTC)

    Returns:
        dict matching Epic 6 §9 #20+ "원가 예측 보고서" envelope schema:
        {
            "report_code": "COST_PREDICTION",
            "title": "원가 예측 보고서",
            "period_key": str,
            "projection_month": str,
            "baseline_summary": {...},
            "projection_inputs": {...},
            "projection_results": {...},
            "generated_at_kst": str (ISO 8601)
        }

    Note:
        This is a PURE serializer — no I/O, no DB access. The actual
        PDF byte rendering is delegated to `packages.services.m6_reports.pdf_helpers`
        (Epic 6 M5 reuse pattern).
    """
    if generated_at_kst is None:
        # Use ISO 8601 UTC for envelope timestamp (PDF renderer can localize).
        generated_at_kst = datetime.now(UTC).isoformat()

    baseline_summary = {
        "fixed_cost": str(baseline.fixed_cost),
        "unit_variable_cost": str(baseline.unit_variable_cost),
        "unit_price": str(baseline.unit_price),
        "operating_rate": str(baseline.operating_rate),
        "target_profit": str(baseline.target_profit),
    }

    projection_inputs_dict = {
        "loan_amount": str(projection_inputs.loan_amount),
        "interest_rate": str(projection_inputs.interest_rate),
        "cost_inflation_rate": str(projection_inputs.cost_inflation_rate),
        "corporate_tax_rate": str(projection_inputs.corporate_tax_rate),
    }

    projection_results = {
        "projected_revenue": str(projection.projected_revenue),
        "projected_variable_cost": str(projection.projected_variable_cost),
        "projected_fixed_cost": str(projection.projected_fixed_cost),
        "interest_expense": str(projection.interest_expense),
        "pre_tax_income": str(projection.pre_tax_income),
        "corporate_tax": str(projection.corporate_tax),
        "after_tax_income": str(projection.after_tax_income),
    }

    return {
        "report_code": PROJECTION_PDF_REPORT_CODE,
        "title": PROJECTION_PDF_TITLE_KO,
        "period_key": period_key,
        "projection_month": projection_month,
        "baseline_summary": baseline_summary,
        "projection_inputs": projection_inputs_dict,
        "projection_results": projection_results,
        "generated_at_kst": generated_at_kst,
    }


__all__ = [
    "PROJECTION_PDF_REPORT_CODE",
    "PROJECTION_PDF_TITLE_KO",
    "serialize_projection_pdf_envelope",
]
