#!/usr/bin/env python3
"""Regenerate docs/STACK_PIN.yaml from ARCHITECTURE-SPINE.md §Stack.

This script is the canonical regenerator for STACK_PIN.yaml. The yaml is the
source of truth for `check_stack_pin.{mjs,py}`; the spine is the source of
truth for *what to put in* the yaml.

Usage:
    python scripts/regenerate_stack_pin.py [--dry-run] [--spine PATH]

Default spine path: _bmad-output/planning-artifacts/architecture/architecture-costmgr-2026-07-24/ARCHITECTURE-SPINE.md
Default output path: docs/STACK_PIN.yaml

The parser is intentionally narrow: it reads the markdown table under
`## §Stack` (or any header containing "Stack") and emits yaml with the same
keys. Packages not present in the spine (e.g., HANDOFF L3 variance items like
pydantic-core 2.27.2) are preserved verbatim from the existing yaml.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover — uv workspace provides PyYAML at runtime
    sys.stderr.write(
        "PyYAML not installed. Run via `uv run python scripts/regenerate_stack_pin.py`.\n"
    )
    sys.exit(2)


def parse_spine_table(spine_text: str) -> dict[str, str]:
    """Extract the §Stack markdown table into {name: version} pairs."""
    table_re = re.compile(
        r"^\|\s*(?P<name>[^|]+?)\s*\|\s*(?P<version>[^|]+?)\s*\|\s*(?P<loc>[^|]+?)\s*\|\s*$",
        re.MULTILINE,
    )
    out: dict[str, str] = {}
    for m in table_re.finditer(spine_text):
        name = m.group("name").strip().lower()
        version = m.group("version").strip()
        # Skip header separator rows like |---|---|
        if version.startswith("---") or name == "name":
            continue
        out[name] = version
    return out


def merge(existing: dict, from_spine: dict) -> dict:
    """Spine wins for keys present in both; existing yaml wins for keys that
    are HANDOFF L3 variance (preserved verbatim with a note).

    CASCADE-2 (CR 2026-07-25): preserve ALL `notes[k]` fields (current,
    reason, spec, owner, deadline) — only stamp `spec` if missing.
    """
    merged = dict(existing.get("stack_pin", {}))
    notes: dict = {}
    for k, v in (existing.get("notes") or {}).items():
        notes[k] = dict(v)  # deep copy
    for k, v in from_spine.items():
        if k not in merged or merged.get(k) != v:
            if k in merged and merged[k] != v:
                notes.setdefault(k, {})["spec"] = v
            merged[k] = v
    return {"stack_pin": merged, "notes": notes}


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--spine", type=Path, default=None, help="Path to ARCHITECTURE-SPINE.md")
    p.add_argument("--out", type=Path, default=Path("docs/STACK_PIN.yaml"))
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    spine_path = (
        args.spine
        or Path("_bmad-output/planning-artifacts/architecture/architecture-costmgr-2026-07-24/ARCHITECTURE-SPINE.md")
    )
    if not spine_path.exists():
        sys.stderr.write(f"spine not found: {spine_path}\n")
        return 1
    spine_text = spine_path.read_text(encoding="utf-8")
    from_spine = parse_spine_table(spine_text)
    if not from_spine:
        sys.stderr.write("no stack table parsed from spine — aborting\n")
        return 1

    existing: dict = {}
    if args.out.exists():
        existing = yaml.safe_load(args.out.read_text(encoding="utf-8")) or {}
    merged = merge(existing, from_spine)

    header = """# ─────────────────────────────────────────────────────────────────────────────
# docs/STACK_PIN.yaml — Canonical stack pin (single source of truth)
# ─────────────────────────────────────────────────────────────────────────────
# AUTO-REGENERATED by scripts/regenerate_stack_pin.py from
# ARCHITECTURE-SPINE.md §Stack. Hand-edit only the `notes` block (HANDOFF L3
# variance) — `stack_pin` is overwritten on regen.
# ─────────────────────────────────────────────────────────────────────────────
"""

    rendered = header + yaml.safe_dump(merged, sort_keys=False, allow_unicode=True)
    if args.dry_run:
        sys.stdout.write(rendered)
        return 0
    args.out.write_text(rendered, encoding="utf-8")
    sys.stdout.write(f"wrote {args.out} ({len(merged['stack_pin'])} keys)\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())